"""change_username_to_email

Revision ID: 4bf59decb76c
Revises: 086d007e3561
Create Date: 2025-09-05 17:55:23.939229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bf59decb76c'
down_revision: Union[str, Sequence[str], None] = '086d007e3561'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Step 1: Add email column as nullable first
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=True))
    
    # Step 2: Update existing users - convert username to email format
    connection = op.get_bind()
    connection.execute(sa.text("UPDATE users SET email = username || '@example.com' WHERE email IS NULL"))
    
    # Step 3: Make email column non-nullable and unique
    op.alter_column('users', 'email', nullable=False)
    
    # Step 4: Create index and drop old one
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_column('users', 'username')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
